// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "CalculatorGUI.h"
#include "Calculator.h"
Calculator c; 
std::string a = ""; 
std::string b = ""; 

static void cb_Calculator(Fl_Double_Window*, void*) {
  display->value(0);
}

Fl_Group *calcDigits=(Fl_Group *)0;

static void cb_1(Fl_Button*, void*) {
  a += "1";
display->value(a.data());
}

Fl_Group *calcFunctions=(Fl_Group *)0;

Fl_Button *clear=(Fl_Button *)0;

static void cb_clear(Fl_Button*, void*) {
  c.addition(0, 0);
a = "";
display->value(0);
}

Fl_Output *display=(Fl_Output *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(189, 306, "Calculator");
    w = o; if (w) {/* empty */}
    o->callback((Fl_Callback*)cb_Calculator);
    { calcDigits = new Fl_Group(10, 81, 171, 229);
      { new Fl_Button(10, 130, 35, 35, "7");
      } // Fl_Button* o
      { new Fl_Button(55, 130, 35, 35, "8");
      } // Fl_Button* o
      { new Fl_Button(100, 130, 35, 35, "9");
      } // Fl_Button* o
      { new Fl_Button(10, 175, 35, 35, "4");
      } // Fl_Button* o
      { new Fl_Button(55, 175, 35, 35, "5");
      } // Fl_Button* o
      { new Fl_Button(100, 175, 35, 35, "6");
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(10, 220, 35, 35, "1");
        o->callback((Fl_Callback*)cb_1);
      } // Fl_Button* o
      { new Fl_Button(55, 220, 35, 35, "2");
      } // Fl_Button* o
      { new Fl_Button(100, 220, 35, 35, "3");
      } // Fl_Button* o
      { new Fl_Button(10, 265, 80, 35, "0");
      } // Fl_Button* o
      calcDigits->end();
    } // Fl_Group* calcDigits
    { calcFunctions = new Fl_Group(10, 86, 170, 219);
      { clear = new Fl_Button(10, 86, 35, 35, "C");
        clear->callback((Fl_Callback*)cb_clear);
      } // Fl_Button* clear
      { new Fl_Button(55, 86, 35, 35, "+-");
      } // Fl_Button* o
      { new Fl_Button(100, 86, 35, 35, "%");
      } // Fl_Button* o
      { new Fl_Return_Button(144, 265, 36, 35, "=");
      } // Fl_Return_Button* o
      { new Fl_Button(100, 265, 35, 35, ".");
      } // Fl_Button* o
      { new Fl_Button(145, 86, 35, 35, "/");
      } // Fl_Button* o
      { new Fl_Button(145, 130, 35, 35, "X");
      } // Fl_Button* o
      { new Fl_Button(145, 175, 35, 35, "-");
      } // Fl_Button* o
      { new Fl_Button(145, 220, 35, 35, "+");
      } // Fl_Button* o
      calcFunctions->end();
    } // Fl_Group* calcFunctions
    { display = new Fl_Output(10, 7, 170, 73);
    } // Fl_Output* display
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
